name: Build all

on:
  workflow_dispatch: # allows for manual dispatch
    inputs:
      build-deps-only:
        description: "Only build dependencies (bypasses caching)"
        type: boolean
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_all:
    name: Build All
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-20.04
          - os: ubuntu-24.04
          - os: windows-latest
          - os: macos-14
            arch: x86_64
          - os: macos-14
            arch: arm64
    uses: ./.github/workflows/build_check_cache.yml
    with:
      os: ${{ matrix.os }}
      arch: ${{ matrix.arch }}
      build-deps-only: ${{ inputs.build-deps-only || false }}
    secrets: inherit
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-46
      options: --privileged
    steps:
      # maybe i'm too dumb and fucked up to do CI. OH WELL :D -ppd
      - name: "Remove unneeded stuff to free disk space"
        run: sudo rm -rf /usr/share/dotnet /opt/ghc "/usr/local/share/boost" "$AGENT_TOOLSDIRECTORY"
      - uses: actions/checkout@v4
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: orcaslicer.flatpak
          manifest-path: flatpak/io.github.softfever.OrcaSlicer.yml
          cache-key: flatpak-builder-${{ github.sha }}
          cache: false
